const fs = require("fs");
const fsp = require("fs/promises");
const path = require("path");
const ExcelJS = require("exceljs");
const PDFDocument = require("pdfkit");
const ReportModel = require("../models/report.model");
const { maskPhoneNumber } = require("./pii.service");

const backendRoot = path.resolve(__dirname, "../..");
const reportRoot = path.resolve(backendRoot, "generated", "reports");

const parseJson = (value) => typeof value === "string" ? JSON.parse(value) : value;
const csvValue = (value) => `"${String(value ?? "").replaceAll('"', '""')}"`;
const formatPortalDateTime = (value, portal) => {
  if (!value) return "";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "";
  const parts = new Intl.DateTimeFormat("en-BZ", {
    timeZone: portal.timeZone,
    year: "numeric", month: "2-digit", day: "2-digit",
    hour: "2-digit", minute: "2-digit", hour12: portal.timeFormat === "12 Hour",
  }).formatToParts(date);
  const get = (type) => parts.find((part) => part.type === type)?.value || "";
  const formattedDate = portal.dateFormat === "MM/DD/YYYY"
    ? `${get("month")}/${get("day")}/${get("year")}`
    : portal.dateFormat === "YYYY-MM-DD"
      ? `${get("year")}-${get("month")}-${get("day")}`
      : `${get("day")}/${get("month")}/${get("year")}`;
  const period = portal.timeFormat === "12 Hour" ? ` ${get("dayPeriod")}` : "";
  return `${formattedDate} ${get("hour")}:${get("minute")}${period}`.trim();
};

const columnsFor = (settings) => {
  const columns = [
    ["Ticket Number", "token_number"], ["Status", "status"], ["Priority", "ticket_priority"],
    ["Category", "category_name"], ["Department", "assigned_department_name"],
    ["Location", "location_name"], ["Submitted", "created_at"], ["Due", "due_at"],
    ["Resolved", "resolved_at"], ["Closed", "closed_at"],
  ];
  if (settings.reports.includeCitizenDetails) {
    columns.push(["Complainant", "comp_name"], ["Phone", "comp_phone"], ["Email", "comp_email"], ["Identification", "identification_number_last4"]);
  }
  return columns;
};

const normalizeRows = (rows, settings) => rows.map((row) => {
  const normalized = { ...row };
  for (const field of ["created_at", "due_at", "resolved_at", "closed_at"]) {
    normalized[field] = formatPortalDateTime(normalized[field], settings.portal);
  }
  if (settings.reports.maskSensitiveDataInReports || settings.privacy.maskCitizenPhoneNumber) normalized.comp_phone = maskPhoneNumber(normalized.comp_phone);
  if (settings.reports.maskSensitiveDataInReports || settings.privacy.maskIdentificationNumber) {
    normalized.identification_number_last4 = normalized.identification_number_last4 ? `****${normalized.identification_number_last4}` : "";
  }
  return normalized;
});

const headerLines = (settings, requestedBy) => {
  const lines = [settings.reports.reportHeaderTitle];
  if (settings.reports.showGeneratedBy) lines.push(`Generated by: ${requestedBy?.name || requestedBy?.email || "Administrator"}`);
  if (settings.reports.showGeneratedDate) lines.push(`Generated: ${formatPortalDateTime(new Date(), settings.portal)}`);
  return lines;
};

const createCsv = async ({ filePath, rows, columns, headers }) => {
  const lines = [...headers.map((line) => csvValue(line)), columns.map(([label]) => csvValue(label)).join(",")];
  for (const row of rows) lines.push(columns.map(([, key]) => csvValue(row[key])).join(","));
  await fsp.writeFile(filePath, `\ufeff${lines.join("\r\n")}\r\n`, "utf8");
};

const createExcel = async ({ filePath, rows, columns, headers }) => {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = headers[1] || "GRM Portal";
  const sheet = workbook.addWorksheet("Grievances");
  headers.forEach((line) => sheet.addRow([line]));
  sheet.addRow([]);
  sheet.columns = columns.map(([label, key]) => ({ header: label, key, width: Math.max(16, label.length + 2) }));
  const headingRow = sheet.getRow(headers.length + 2);
  columns.forEach(([label], index) => { headingRow.getCell(index + 1).value = label; });
  headingRow.font = { bold: true, color: { argb: "FFFFFFFF" } };
  headingRow.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF12355B" } };
  rows.forEach((row) => sheet.addRow(row));
  sheet.views = [{ state: "frozen", ySplit: headers.length + 2 }];
  await workbook.xlsx.writeFile(filePath);
};

const createPdf = ({ filePath, rows, columns, headers, logoPath }) => new Promise((resolve, reject) => {
  const document = new PDFDocument({ margin: 36, size: "A4", layout: "landscape", bufferPages: true });
  const stream = fs.createWriteStream(filePath);
  stream.on("finish", resolve); stream.on("error", reject); document.on("error", reject); document.pipe(stream);
  if (logoPath && fs.existsSync(logoPath)) {
    try { document.image(logoPath, 36, 30, { fit: [70, 45] }); } catch {}
  }
  document.fontSize(16).fillColor("#12355b").text(headers[0], { align: "center" });
  headers.slice(1).forEach((line) => document.fontSize(8).fillColor("#4b5563").text(line, { align: "center" }));
  document.moveDown();
  const visibleColumns = columns.slice(0, 8);
  const widths = [90, 70, 55, 100, 100, 80, 105, 105];
  const drawRow = (values, bold = false) => {
    const y = document.y; if (y > 540) { document.addPage(); }
    const currentY = document.y;
    values.forEach((value, index) => document.font(bold ? "Helvetica-Bold" : "Helvetica").fontSize(7).fillColor("#172033").text(String(value ?? ""), 36 + widths.slice(0, index).reduce((a, b) => a + b, 0), currentY, { width: widths[index] - 5, height: 28, ellipsis: true }));
    document.y = currentY + 30;
  };
  drawRow(visibleColumns.map(([label]) => label), true);
  rows.forEach((row) => drawRow(visibleColumns.map(([, key]) => row[key])));
  document.end();
});

const resolveLogo = (settings) => {
  if (!settings.reports.showOrganizationLogo || !settings.organization.logo) return null;
  const relativeUrl = String(settings.organization.logo).replace(/^https?:\/\/[^/]+/i, "").replace(/^\/uploads\//, "uploads/");
  const absolute = path.resolve(backendRoot, relativeUrl);
  const allowed = path.resolve(backendRoot, "uploads", "settings");
  const relative = path.relative(allowed, absolute);
  return relative && !relative.startsWith("..") && !path.isAbsolute(relative) ? absolute : null;
};

const processNext = async () => {
  const job = await ReportModel.claimNext();
  if (!job) return false;
  try {
    const settings = parseJson(job.settings_snapshot);
    const filters = parseJson(job.filters);
    const [sourceRows, requestedBy] = await Promise.all([
      ReportModel.loadRows({ filters, maximumRecords: settings.reports.maximumExportRecords }),
      ReportModel.getRequestedBy(job.requested_by),
    ]);
    const rows = normalizeRows(sourceRows, settings);
    const columns = columnsFor(settings);
    const headers = headerLines(settings, requestedBy);
    await fsp.mkdir(reportRoot, { recursive: true });
    const extension = job.output_format === "PDF" ? "pdf" : job.output_format === "Excel" ? "xlsx" : "csv";
    const outputName = `grievance-report-${job.id}.${extension}`;
    const filePath = path.join(reportRoot, outputName);
    let mimeType;
    if (job.output_format === "PDF") {
      mimeType = "application/pdf";
      await createPdf({ filePath, rows, columns, headers, logoPath: resolveLogo(settings) });
    } else if (job.output_format === "Excel") {
      mimeType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
      await createExcel({ filePath, rows, columns, headers });
    } else {
      mimeType = "text/csv; charset=utf-8";
      await createCsv({ filePath, rows, columns, headers });
    }
    await ReportModel.complete({ id: job.id, totalRecords: rows.length, outputPath: path.relative(backendRoot, filePath).replace(/\\/g, "/"), outputName, mimeType });
  } catch (error) { await ReportModel.fail(job.id, error.message); }
  return true;
};

module.exports = { formatPortalDateTime, processNext, reportRoot };
