const express = require("express");
const { verifyToken } = require("../middlewares/auth.middleware");
const { checkAnyPermission, checkPermission } = require("../middlewares/permission.middleware");
const controller = require("../controllers/configuration.controller");
const directory = require("../controllers/site-directory.controller");
const { handleDirectoryImageUpload } = require("../middlewares/directory-image.middleware");

const router = express.Router();
router.use(verifyToken);
router.get("/", checkAnyPermission(["configuration.catalogs.manage", "configuration.routing.manage", "configuration.workflow.manage", "configuration.departments.manage", "configuration.form_options.manage", "configuration.intake_classifications.manage", "departments.view", "departments.manage", "departments.manage_limited"]), controller.getConfiguration);
router.get("/intake-classifications", checkPermission("configuration.intake_classifications.manage"), controller.getIntakeClassifications);
router.post("/intake-classifications", checkPermission("configuration.intake_classifications.manage"), controller.saveIntakeClassification);
router.put("/intake-classifications/:id", checkPermission("configuration.intake_classifications.manage"), controller.saveIntakeClassification);
router.delete("/intake-classifications/:id", checkPermission("configuration.intake_classifications.manage"), controller.deactivateIntakeClassification);
router.get("/site-directory", checkAnyPermission(["configuration.catalogs.manage", "configuration.departments.manage", "departments.view", "departments.manage", "departments.manage_limited"]), directory.getDirectoryConfiguration);
router.put("/site-directory/departments/:id", checkAnyPermission(["configuration.catalogs.manage", "configuration.departments.manage", "departments.manage"]), directory.saveDepartmentProfile);
router.post("/site-directory/facilities", checkAnyPermission(["configuration.catalogs.manage", "configuration.departments.manage", "departments.manage"]), directory.saveFacility);
router.put("/site-directory/facilities/:id", checkAnyPermission(["configuration.catalogs.manage", "configuration.departments.manage", "departments.manage"]), directory.saveFacility);
router.post("/site-directory/facilities/:id/image", checkAnyPermission(["configuration.catalogs.manage", "configuration.departments.manage", "departments.manage"]), handleDirectoryImageUpload, directory.uploadFacilityImage);
router.post("/site-directory/:ownerType/:ownerId/contacts", checkAnyPermission(["configuration.catalogs.manage", "configuration.departments.manage", "departments.manage"]), directory.saveContact);
router.put("/site-directory/:ownerType/:ownerId/contacts/:contactId", checkAnyPermission(["configuration.catalogs.manage", "configuration.departments.manage", "departments.manage"]), directory.saveContact);
router.post("/site-directory/social-links", checkAnyPermission(["configuration.catalogs.manage", "configuration.departments.manage", "departments.manage"]), directory.saveSocialLink);
router.put("/site-directory/social-links/:id", checkAnyPermission(["configuration.catalogs.manage", "configuration.departments.manage", "departments.manage"]), directory.saveSocialLink);
router.post("/catalogs/:catalog", checkAnyPermission(["configuration.catalogs.manage", "configuration.departments.manage", "departments.manage"]), controller.saveCatalogItem);
router.put("/catalogs/:catalog/:id", checkAnyPermission(["configuration.catalogs.manage", "configuration.departments.manage", "departments.manage"]), controller.saveCatalogItem);
router.delete("/catalogs/:catalog/:id", checkAnyPermission(["configuration.catalogs.manage", "configuration.departments.manage", "departments.manage"]), controller.deactivateCatalogItem);
router.put("/categories/:id/departments", checkAnyPermission(["configuration.catalogs.manage", "configuration.departments.manage", "departments.manage"]), controller.saveCategoryMappings);
router.post("/statuses", checkPermission("configuration.workflow.manage"), controller.saveStatus);
router.put("/statuses/:id", checkPermission("configuration.workflow.manage"), controller.saveStatus);
router.post("/priorities", checkPermission("configuration.workflow.manage"), controller.savePriority);
router.put("/priorities/:id", checkPermission("configuration.workflow.manage"), controller.savePriority);
router.delete("/workflow/:type/:id", checkPermission("configuration.workflow.manage"), controller.deactivateWorkflowItem);
router.put("/transitions", checkPermission("configuration.workflow.manage"), controller.saveTransition);
router.post("/form-options", checkPermission("configuration.form_options.manage"), controller.saveFormOption);
router.put("/form-options/:id", checkPermission("configuration.form_options.manage"), controller.saveFormOption);
router.delete("/form-options/:id", checkPermission("configuration.form_options.manage"), controller.deactivateFormOption);
router.post("/routing-rules", checkPermission("configuration.routing.manage"), controller.saveRoutingRule);
router.put("/routing-rules/:id", checkPermission("configuration.routing.manage"), controller.saveRoutingRule);
router.delete("/routing-rules/:id", checkPermission("configuration.routing.manage"), controller.deactivateRoutingRule);
router.post("/holidays", checkPermission("configuration.catalogs.manage"), controller.saveHoliday);
router.put("/holidays/:id", checkPermission("configuration.catalogs.manage"), controller.saveHoliday);
router.delete("/holidays/:id", checkPermission("configuration.catalogs.manage"), controller.deactivateHoliday);

module.exports = router;
