const option = (value) => ({ label: value, value });
const options = (values) => values.map(option);

export const settingsSections = [
  {
    id: "organization", title: "Organization Information", icon: "globe", description: "Government identity and official contact details.",
    fields: [
      { key: "organizationName", label: "Organization Name", required: true, full: true },
      { key: "portalName", label: "Portal Name", required: true },
      { key: "organizationShortName", label: "Organization Short Name", required: true },
      { key: "logo", label: "Organization Logo", type: "file", assetType: "logo", full: true },
      { key: "favicon", label: "Favicon", type: "file", assetType: "favicon", full: true },
      { key: "officialEmail", label: "Official Email", type: "email" },
      { key: "officialPhone", label: "Official Phone Number", type: "tel" },
      { key: "officialPhoneLabel", label: "Official Phone Label", help: "Displayed beside the official number in the public header." },
      { key: "websiteUrl", label: "Website URL", type: "url", full: true },
      { key: "officeAddress", label: "Office Address", type: "textarea", rows: 3, full: true },
      { key: "country", label: "Country", required: true },
      { key: "defaultLocation", label: "Default District or Location" },
      { key: "settingsUploadMaxKb", label: "Maximum Branding File Size", type: "number", min: 100, max: 5120, suffix: "KB", help: "Applies to logo and favicon uploads." },
    ],
  },
  {
    id: "portal", title: "Portal Configuration", icon: "settings", description: "Regional formats, display defaults, and maintenance controls.",
    fields: [
      { key: "portalTitle", label: "Portal Title", required: true, full: true },
      { key: "portalSubtitle", label: "Portal Subtitle", full: true },
      { key: "defaultLanguage", label: "Default Language", type: "select", options: options(["English", "Spanish"]) },
      { key: "dateFormat", label: "Date Format", type: "select", options: options(["DD/MM/YYYY", "MM/DD/YYYY", "YYYY-MM-DD"]) },
      { key: "timeFormat", label: "Time Format", type: "select", options: options(["12 Hour", "24 Hour"]) },
      { key: "timeZone", label: "Time Zone" },
      { key: "recordsPerPage", label: "Records Per Page", type: "number", min: 5, max: 200 },
      { key: "defaultDashboardPeriod", label: "Default Dashboard Period", type: "select", options: options(["Last 7 Days", "Last 30 Days", "Current Month", "Current Quarter", "Current Year"]) },
      { key: "maintenanceMode", label: "Maintenance Mode", type: "toggle", help: "Temporarily prevent public portal access." },
      { key: "maintenanceMessage", label: "Maintenance Message", type: "textarea", rows: 3, full: true, showWhen: ["maintenanceMode", true] },
    ],
  },
  {
    id: "grievanceSubmission", title: "Grievance Submission", icon: "grievances", description: "Control public intake requirements and attachments.",
    fields: [
      { key: "allowPublicSubmission", label: "Allow Public Grievance Submission", type: "toggle" },
      { key: "allowAnonymousComplaints", label: "Allow Anonymous Complaints", type: "toggle" },
      { key: "mobileNumberRequired", label: "Mobile Number Required", type: "toggle" },
      { key: "emailAddressRequired", label: "Email Address Required", type: "toggle" },
      { key: "identificationNumberRequired", label: "Identification Number Required", type: "toggle", runtimeCapability: "pii", unavailableHelp: "Configure PII encryption before collecting identification numbers." },
      { key: "allowCitizenDepartmentSelection", label: "Allow Citizen to Select Department", type: "toggle" },
      { key: "allowCitizenCategorySelection", label: "Allow Citizen to Select Category", type: "toggle" },
      { key: "allowMultipleAttachments", label: "Allow Multiple Attachments", type: "toggle" },
      { key: "maximumAttachmentCount", label: "Maximum Attachment Count", type: "number", min: 1, max: 10, suffix: "files", showWhen: ["allowMultipleAttachments", true] },
      { key: "maximumAttachmentSizeMb", label: "Maximum Attachment Size", type: "number", min: 1, max: 25, suffix: "MB" },
      { key: "allowedFileTypes", label: "Allowed File Types", type: "multiselect", dynamicOptions: "attachmentTypes", full: true },
      { key: "maximumDescriptionLength", label: "Maximum Description Length", type: "number", min: 250, max: 50000, suffix: "characters" },
      { key: "enableCaptcha", label: "Enable CAPTCHA", type: "toggle", runtimeCapability: "captcha", unavailableHelp: "Configure the reCAPTCHA site and secret keys before enabling CAPTCHA." },
      { key: "displayDeclarationCheckbox", label: "Display Declaration Checkbox", type: "toggle" },
      { key: "declarationText", label: "Declaration Text", type: "textarea", rows: 3, full: true, showWhen: ["displayDeclarationCheckbox", true] },
    ],
  },
  {
    id: "ticket", title: "Acknowledgement and Tracking", icon: "key", description: "Configure confirmation and public tracking. Ticket generation is managed in Ticket Number Format.",
    fields: [
      { key: "displayTicketOnConfirmation", label: "Display Ticket on Confirmation Page", type: "toggle" },
      { key: "sendSubmissionAcknowledgement", label: "Send Submission Acknowledgement", type: "toggle" },
      { key: "acknowledgementMessage", label: "Acknowledgement Message", type: "textarea", rows: 3, full: true, showWhen: ["sendSubmissionAcknowledgement", true] },
      { key: "allowPublicTicketTracking", label: "Allow Public Ticket Tracking", type: "toggle" },
      { key: "trackingVerificationMethod", label: "Tracking Verification Method", type: "select", full: true, options: options(["Ticket Number Only", "Ticket Number and Phone Number", "Ticket Number and Email Address", "Ticket Number and Identification Number"]) },
    ],
  },
  {
    id: "assignment", title: "Assignment Settings", icon: "users", description: "Set assignment ownership, priority, and reassignment rules.",
    fields: [
      { key: "defaultAssignmentMethod", label: "Default Assignment Method", type: "select", options: options(["Manual", "Automatic", "Category-Based", "Department-Based", "Location-Based"]) },
      { key: "allowAdminAssignment", label: "Allow Admin Assignment", type: "toggle" },
      { key: "allowDepartmentReassignmentRequest", label: "Allow Department Reassignment Request", type: "toggle" },
      { key: "allowDirectDepartmentReassignment", label: "Allow Direct Department Reassignment", type: "toggle" },
      { key: "departmentOfficerSelectionRequired", label: "Department Officer Selection Required", type: "toggle" },
      { key: "internalAssignmentNoteRequired", label: "Internal Assignment Note Required", type: "toggle" },
      { key: "defaultAssignmentPriority", label: "Default Assignment Priority", type: "select", dynamicOptions: "priorities" },
      { key: "notifyDepartmentOnAssignment", label: "Notify Department on Assignment", type: "toggle" },
    ],
  },
  {
    id: "dueDate", title: "Due Date and Escalation", icon: "clock", description: "Define resolution timelines, reminders, extensions, and escalation.",
    fields: [
      { key: "dueDateRequired", label: "Due Date Required", type: "toggle" },
      { key: "defaultResolutionDays", label: "Default Resolution Days", type: "number", min: 1, max: 365, showWhen: ["dueDateRequired", true] },
      { key: "countWorkingDaysOnly", label: "Count Working Days Only", type: "toggle", showWhen: ["dueDateRequired", true] },
      { key: "excludePublicHolidays", label: "Exclude Public Holidays", type: "toggle", showWhen: ["dueDateRequired", true] },
      { key: "dueDateReminderDays", label: "Due-Date Reminder Days", type: "number", min: 1, max: 90, showWhen: ["dueDateRequired", true] },
      { key: "automaticallyMarkOverdue", label: "Automatically Mark as Overdue", type: "toggle", showWhen: ["dueDateRequired", true] },
      { key: "allowDepartmentChangeDueDate", label: "Allow Department to Change Due Date", type: "toggle", showWhen: ["dueDateRequired", true] },
      { key: "adminApprovalDueDateExtension", label: "Admin Approval Required for Due-Date Extension", type: "toggle", showWhen: ["dueDateRequired", true] },
      { key: "enableEscalation", label: "Enable Escalation", type: "toggle" },
      { key: "escalateAfterDays", label: "Escalate After Number of Days", type: "number", min: 1, max: 365, showWhen: ["enableEscalation", true] },
    ],
  },
  {
    id: "workflow", title: "Workflow Settings", icon: "activity", description: "Control reviews, approvals, reopening, and automated closure.", preview: "workflow",
    fields: [
      { key: "defaultNewGrievanceStatus", label: "Default New Grievance Status", type: "select", dynamicOptions: "statuses" },
      { key: "adminReviewRequired", label: "Admin Review Required", type: "toggle" },
      { key: "departmentAcceptanceRequired", label: "Department Acceptance Required", type: "toggle" },
      { key: "adminApprovalBeforeClosure", label: "Admin Approval Before Closure", type: "toggle" },
      { key: "allowReopening", label: "Allow Reopening", type: "toggle" },
      { key: "reopenPermission", label: "Reopen Permission", type: "select", options: options(["Super Admin Only", "Super Admin and Admin"]), showWhen: ["allowReopening", true] },
      { key: "requireCommentOnStatusChange", label: "Require Comment on Status Change", type: "toggle" },
      { key: "requireResolutionDocument", label: "Require Resolution Document", type: "toggle" },
      { key: "resolutionDocumentMaximumSizeMb", label: "Resolution Document Maximum Size", type: "number", min: 1, max: 25, suffix: "MB" },
      { key: "resolutionDocumentAllowedFileTypes", label: "Resolution Document File Types", type: "multiselect", dynamicOptions: "attachmentTypes", full: true },
      { key: "autoCloseResolvedGrievances", label: "Auto-Close Resolved Grievances", type: "toggle" },
      { key: "autoCloseAfterDays", label: "Auto-Close After Number of Days", type: "number", min: 1, max: 365, showWhen: ["autoCloseResolvedGrievances", true] },
    ],
  },
  {
    id: "notifications", title: "Notification Settings", icon: "bell", description: "Choose channels and operational events that trigger notifications.",
    fields: [
      ["enableEmailNotifications", "Enable Email Notifications", "email"], ["enableDashboardNotifications", "Enable Dashboard Notifications"],
      ["notifySuperAdminNewGrievance", "Notify Super Admin on New Grievance"], ["notifyAdminNewGrievance", "Notify Admin on New Grievance"], ["notifyDepartmentOnAssignment", "Notify Department on Assignment"], ["notifyCitizenStatusChange", "Notify Citizen on Status Change"],
      ["notifyDueDateReminder", "Notify on Due-Date Reminder"], ["notifyOverdueGrievance", "Notify on Overdue Grievance"], ["notifyAdminResolutionSubmission", "Notify Admin on Resolution Submission"], ["notifyDepartmentResolutionReturned", "Notify Department When Resolution Is Returned"], ["notifyCitizenGrievanceClosed", "Notify Citizen When Grievance Is Closed"],
    ].map(([key, label, runtimeCapability]) => ({
      key, label, type: "toggle", runtimeCapability,
      unavailableHelp: runtimeCapability === "email" ? "Configure SMTP before enabling email notifications." : undefined,
    })),
  },
  {
    id: "security", title: "Security Settings", icon: "shieldCheck", description: "Apply account, password, session, and login controls.",
    fields: [
      { key: "minimumPasswordLength", label: "Minimum Password Length", type: "number", min: 8, max: 32 },
      { key: "requireUppercase", label: "Require Uppercase Character", type: "toggle" },
      { key: "requireLowercase", label: "Require Lowercase Character", type: "toggle" },
      { key: "requireNumber", label: "Require Number", type: "toggle" },
      { key: "requireSpecialCharacter", label: "Require Special Character", type: "toggle" },
      { key: "passwordExpiryDays", label: "Password Expiry Period", type: "number", min: 0, max: 3650, suffix: "days" },
      { key: "maximumLoginAttempts", label: "Maximum Login Attempts", type: "number", min: 3, max: 10 },
      { key: "accountLockDurationMinutes", label: "Account Lock Duration", type: "number", min: 5, max: 1440, suffix: "minutes" },
      { key: "sessionTimeoutMinutes", label: "Session Timeout", type: "number", min: 5, max: 1440, suffix: "minutes" },
      { key: "forcePasswordChangeFirstLogin", label: "Force Password Change on First Login", type: "toggle" },
      { key: "enableTwoFactorAuthentication", label: "Enable Two-Factor Authentication", type: "toggle", runtimeCapability: "two_factor", unavailableHelp: "Configure SMTP and the two-factor pepper before enabling two-factor authentication." },
      { key: "restrictConcurrentLogin", label: "Restrict Concurrent Login", type: "toggle" },
    ],
  },
  {
    id: "privacy", title: "Privacy and Data", icon: "lock", description: "Consent, data masking, retention, and public tracking visibility.",
    fields: [
      { key: "privacyNotice", label: "Privacy Notice", type: "textarea", rows: 7, required: true, full: true },
      { key: "termsAndConditions", label: "Terms and Conditions", type: "textarea", rows: 7, required: true, full: true },
      { key: "citizenConsentRequired", label: "Citizen Consent Required", type: "toggle" },
      { key: "maskIdentificationNumber", label: "Mask Identification Number", type: "toggle" },
      { key: "maskCitizenPhoneNumber", label: "Mask Citizen Phone Number", type: "toggle" },
      { key: "dataRetentionMonths", label: "Data Retention Period", type: "number", min: 1, max: 1200, suffix: "months" },
      { key: "allowGrievanceExport", label: "Allow Grievance Export", type: "toggle" },
      { key: "allowAttachmentDownload", label: "Allow Attachment Download", type: "toggle" },
      { key: "publicTrackingDataVisibility", label: "Public Tracking Data Visibility", type: "multiselect", full: true, options: options(["Ticket Number", "Complaint Subject", "Submission Date", "Assigned Department", "Current Status", "Last Updated Date", "Resolution Summary", "Closure Date"]) },
    ],
  },
  {
    id: "dashboard", title: "Dashboard Settings", icon: "dashboard", description: "Choose the operational cards, charts, and panels shown by default.", preview: "dashboard",
    fields: [
      ["showTotalGrievances", "Show Total Grievances"], ["showNewGrievances", "Show New Grievances"], ["showUnassignedGrievances", "Show Unassigned Grievances"], ["showInProgressGrievances", "Show In-Progress Grievances"],
      ["showResolvedGrievances", "Show Resolved Grievances"], ["showOverdueGrievances", "Show Overdue Grievances"], ["showStatusDistributionChart", "Show Status Distribution Chart"], ["showMonthlyTrendChart", "Show Monthly Trend Chart"],
      ["showDepartmentProgress", "Show Department Progress"], ["showRecentActivity", "Show Recent Activity"], ["showHighPriorityCases", "Show High-Priority Cases"], ["showDueTodayPanel", "Show Due-Today Panel"],
    ].map(([key, label]) => ({ key, label, type: "toggle" })),
  },
  {
    id: "reports", title: "Report and Export Settings", icon: "download", description: "Set report identity, formats, access, limits, and masking.",
    fields: [
      { key: "defaultReportFormat", label: "Default Report Format", type: "select", options: options(["PDF", "Excel", "CSV"]) },
      { key: "reportHeaderTitle", label: "Report Header Title", required: true, full: true },
      { key: "showOrganizationLogo", label: "Show Organization Logo", type: "toggle" },
      { key: "showGeneratedBy", label: "Show Generated By", type: "toggle" },
      { key: "showGeneratedDate", label: "Show Generated Date", type: "toggle" },
      { key: "allowAdminExport", label: "Allow Admin Export", type: "toggle" },
      { key: "allowMinistryExport", label: "Allow Ministry Export", type: "toggle" },
      { key: "maximumExportRecords", label: "Maximum Export Records", type: "number", min: 1, max: 1000000 },
      { key: "includeCitizenDetails", label: "Include Citizen Details", type: "toggle" },
      { key: "maskSensitiveDataInReports", label: "Mask Sensitive Data in Reports", type: "toggle" },
    ],
  },
  {
    id: "footer", title: "Footer and Support", icon: "help", description: "Public footer, helpdesk contacts, policy links, and version details.",
    fields: [
      { key: "footerText", label: "Footer Text", type: "textarea", rows: 3, full: true },
      { key: "copyrightYear", label: "Copyright Year", type: "number", min: 2000, max: 2200 },
      { key: "supportEmail", label: "Support Email", type: "email" },
      { key: "supportPhone", label: "Support Phone", type: "tel" },
      { key: "helpdeskWorkingHours", label: "Helpdesk Working Hours", full: true },
      { key: "userGuideUrl", label: "User Guide URL", type: "url", full: true },
      { key: "privacyPolicyUrl", label: "Privacy Policy URL", type: "url", full: true },
      { key: "termsConditionsUrl", label: "Terms and Conditions URL", type: "url", full: true },
    ],
  },
];

export const settingLabels = new Map(
  settingsSections.flatMap((section) =>
    section.fields.map((field) => [`${section.id}.${field.key}`, field.label]),
  ),
);
